### PR TITLE
added json schema for codebing.searchProviders

### PR DESCRIPTION
**Pull request by SrTobi**
look, what I found out: the configuration contribution point is basically a json schema (http://json-schema.org/).

### CODE REVIEW

**Comment by jahands** [comment]
What does this affect exactly? I'm not understanding what this does in this context.
I was hoping maybe vscode would give intellisense when editing searchProviders but that doesn't seem to be the case.

**Comment by SrTobi** [comment]
now, you can hover over the `"g"` in `{ "g": "bla bla" }` and vs code shows a description.

**Comment by jahands** [comment]
Ok that's awesome.
I'd change the description to something like `"A key mapping to a search url. '{query}' is replaced with the search query"`

**Comment by SrTobi** [comment]
review and merge please

**Comment by jahands** [comment]
:+1:

**Pull request merged**
